---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/contacts":
    post:
      summary: Creates a contact
      tags:
      - Contacts
      parameters: []
      responses:
        '201':
          description: contact created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
              required:
              - first_name
              - last_name
              - email
    get:
      summary: Retrieves all contacts
      tags:
      - Contacts
      responses:
        '200':
          description: found Contacts
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  first_name:
                    type: string
                  last_name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - first_name
                - last_name
                - email
        '404':
          description: No contacts not found
          content: {}
  "/v1/sessions":
    post:
      summary: Creates a session
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description: Session created
          content: {}
        '401':
          description: unauthorized request
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/v1/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_comfirmation:
                  type: string
              required:
              - email
              - password
              - password_comfirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:8000
